# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI-CD

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
   # container:
   #   image: golang:1.20.3-alpine
    steps:
      - uses: actions/checkout@v3
        #with:
         #fetch-depth: 1
         #path: go/src/github.com/isaaclyra132/golang-api

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
            go-version: 1.20
            
      - name: Debug
        run: |
          cd /home/runner/work/golang-api/golang-api
          ls
          pwd
          echo ${GOPATH}
          echo ${GOROOT}
      - name: Install dependencies
        run: |
          ls
          go get -v ./...
        env:
          GOPATH: /home/runner/work/golang-api/golang-api

      - name: Verify dependencies
        run: go mod verify
        env:
            GOPATH: /home/runner/work/golang-api/golang-api

      - name: Build
        run: go build -v ./...
        env:
           GOPATH: /home/runner/work/golang-api/golang-api

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/isaaclyra132/golang-api

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          
      - name: Debug
        run: |
          pwd
          echo ${GOPATH}
          echo ${GOROOT}
        env:
          GOPATH: /home/runner/work/golang-api/go
          
      - name: Install dependencies
        run: |
          ls
          go get -v ./
        env:
          GOPATH: /home/runner/work/golang-api/go

      # - name: Verify dependencies
      #   run: go mod verify
      - name: Tests
        run:  |
          ls
          go test -v 
        #env:
         # GOPATH: /home/runner/work/golang-api/

      #- name: Run go vet
       # run: go vet ./...
        #env:
        #  GOPATH: /home/runner/work/golang-api/go
