# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI-CD

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
   # container:
   #   image: golang:1.20.3-alpine
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
            go-version: 1.20.3
          
      - name: Install dependencies
        run: go get -v ./...

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.3
          
      - name: Verify dependencies
        run: go mod verify
            
      - name: Install dependencies
        run: go get -v ./

      - name: Verify dependencies
        run: go mod verify
        
      - name: Tests
        run:  go test -v ./...

      #- name: Run go vet
       # run: go vet ./...
        #env:
        #  GOPATH: /home/runner/work/golang-api/go
